name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for Changes in index.js
        id: check_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "index.js"; then
            echo "DEPLOY=true" >> $GITHUB_ENV
          else
            echo "DEPLOY=false" >> $GITHUB_ENV
          fi

      - name: Zip the Lambda Function
        if: env.DEPLOY == 'true'
        run: zip -r lambda.zip index.js node_modules

      - name: Configure AWS Credentials
        if: env.DEPLOY == 'true'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        if: env.DEPLOY == 'true'
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip

      - name: Skip Deployment
        if: env.DEPLOY == 'false'
        run: echo "No changes in index.js, skipping deployment."